all: AS FS User PD
	
AS: codigo/AS.c
	gcc -Wall codigo/AS.c codigo/utils.c -o AS
FS: codigo/FS.c
	gcc -Wall codigo/FS.c codigo/utils.c -o FS
User: codigo/User.c
	gcc -Wall codigo/User.c codigo/utils.c -o user
PD: codigo/PD.c
	gcc -Wall codigo/PD.c codigo/utils.c -o pd
